#!/usr/bin/env bash

detect_wallpaper_dir() {
  local d1="$HOME/Images/wallpapers"
  local d2="$HOME/Imágenes/wallpapers"

  if [[ -d "$d1" ]]; then
    echo "$d1"
    return 0
  fi
  if [[ -d "$d2" ]]; then
    echo "$d2"
    return 0
  fi

  echo "$d1"
}

copy_wallpapers() {
  local src_dir="${REPO_ROOT}/wallpapers"
  local dst_dir
  dst_dir="$(detect_wallpaper_dir)"

  if [[ $DRY_RUN -eq 1 ]]; then
    dry "Se aseguraria directorio de wallpapers: $dst_dir"
  else
    mkdir -p "$dst_dir"
  fi
  if [[ ! -d "$src_dir" ]]; then
    warn "No existe el directorio de wallpapers en el repo: $src_dir"
    echo ""
    return 0
  fi

  shopt -s nullglob
  local files=("$src_dir"/*)
  shopt -u nullglob

  if ((${#files[@]} == 0)); then
    warn "No hay wallpapers para copiar en: $src_dir"
    echo ""
    return 0
  fi

  local f
  for f in "${files[@]}"; do
    if [[ -f "$f" ]]; then
      local target_file="${dst_dir}/$(basename "$f")"
      if [[ ! -e "$target_file" ]]; then
        if [[ $DRY_RUN -eq 1 ]]; then
          dry "Se copiaria wallpaper: $target_file"
        else
          cp -a "$f" "$target_file"
          log "Wallpaper copiado: $target_file"
        fi
      fi
    fi
  done

  echo "$dst_dir"
}

ensure_wal_alacritty_template() {
  local content
  content="$(cat <<'EOF'
# Auto-generated by pywal

[colors.primary]
background = "{background}"
foreground = "{foreground}"

[colors.cursor]
text = "{background}"
cursor = "{foreground}"

[colors.normal]
black   = "{color0}"
red     = "{color1}"
green   = "{color2}"
yellow  = "{color3}"
blue    = "{color4}"
magenta = "{color5}"
cyan    = "{color6}"
white   = "{color7}"

[colors.bright]
black   = "{color8}"
red     = "{color9}"
green   = "{color10}"
yellow  = "{color11}"
blue    = "{color12}"
magenta = "{color13}"
cyan    = "{color14}"
white   = "{color15}"
EOF
)"

  if [[ $DRY_RUN -eq 1 ]]; then
    dry "Se aseguraria directorio de templates de wal: $WAL_TEMPLATES_DIR"
  else
    mkdir -p "$WAL_TEMPLATES_DIR"
  fi

  if [[ -f "$WAL_ALACRITTY_TEMPLATE" ]]; then
    local current
    current="$(cat "$WAL_ALACRITTY_TEMPLATE")"
    if [[ "$current" == "$content" ]]; then
      log "Template de Alacritty para wal ya esta actualizado: $WAL_ALACRITTY_TEMPLATE"
      return 0
    fi
  fi

  safe_write_file "$WAL_ALACRITTY_TEMPLATE" "$content"
  log "Template de Alacritty para wal asegurado en: $WAL_ALACRITTY_TEMPLATE"
}

regenerate_wal_cache() {
  local wallpaper_dir="$1"

  if ! command_exists wal; then
    warn "No se encontro wal (pywal). Se omite regenerar cache de colores."
    return 0
  fi

  if [[ -z "$wallpaper_dir" || ! -d "$wallpaper_dir" ]]; then
    warn "Directorio de wallpapers no valido para wal: $wallpaper_dir"
    return 0
  fi

  if [[ $DRY_RUN -eq 1 ]]; then
    dry "Se ejecutaria: wal -i $wallpaper_dir"
    return 0
  fi

  if wal -i "$wallpaper_dir"; then
    log "Cache de wal regenerada usando: $wallpaper_dir"
  else
    warn "wal no pudo regenerar la cache con: $wallpaper_dir"
  fi
}

ensure_alacritty_wal_import() {
  local import_line='import = ["~/.cache/wal/colors-alacritty.toml"]'

  if [[ ! -f "$ALACRITTY_CONFIG_FILE" ]]; then
    local content
    content="$(cat <<EOF
[general]
$import_line
EOF
)"
    safe_write_file "$ALACRITTY_CONFIG_FILE" "$content"
    log "Creado config de Alacritty con import de wal: $ALACRITTY_CONFIG_FILE"
    return 0
  fi

  if grep -Fq 'colors-alacritty.toml' "$ALACRITTY_CONFIG_FILE"; then
    log "Import de wal ya presente en Alacritty: $ALACRITTY_CONFIG_FILE"
    return 0
  fi

  if [[ $DRY_RUN -eq 1 ]]; then
    dry "Se agregaria import de wal en: $ALACRITTY_CONFIG_FILE"
    return 0
  fi

  local tmp
  tmp="$(mktemp)"

  awk -v import_line="$import_line" '
    BEGIN {
      in_general = 0
      general_seen = 0
      import_set = 0
    }

    /^[[:space:]]*\[[^]]+\][[:space:]]*$/ {
      if (in_general && !import_set) {
        print import_line
        import_set = 1
      }

      if ($0 ~ /^[[:space:]]*\[general\][[:space:]]*$/) {
        in_general = 1
        general_seen = 1
      } else {
        in_general = 0
      }

      print
      next
    }

    {
      if (in_general && $0 ~ /^[[:space:]]*import[[:space:]]*=/) {
        print import_line
        import_set = 1
        next
      }

      print
    }

    END {
      if (!general_seen) {
        print ""
        print "[general]"
        print import_line
      } else if (in_general && !import_set) {
        print import_line
      }
    }
  ' "$ALACRITTY_CONFIG_FILE" > "$tmp"

  if ! cmp -s "$ALACRITTY_CONFIG_FILE" "$tmp"; then
    backup_file_once "$ALACRITTY_CONFIG_FILE"
    cat "$tmp" > "$ALACRITTY_CONFIG_FILE"
    log "Agregado import de wal en Alacritty: $ALACRITTY_CONFIG_FILE"
  else
    log "Alacritty ya estaba en estado correcto: $ALACRITTY_CONFIG_FILE"
  fi

  rm -f "$tmp"
}
