#!/usr/bin/env bash

ALACRITTY_BASE_COLORS_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/alacritty/colors-base.toml"

detect_wallpaper_dir() {
  local d1="$HOME/Images/wallpapers"
  local d2="$HOME/Imágenes/wallpapers"

  if [[ -d "$d1" ]]; then
    echo "$d1"
    return 0
  fi
  if [[ -d "$d2" ]]; then
    echo "$d2"
    return 0
  fi

  echo "$d1"
}

copy_wallpapers() {
  local src_dir="${REPO_ROOT}/wallpapers"
  local dst_dir
  dst_dir="$(detect_wallpaper_dir)"

  if [[ $DRY_RUN -eq 1 ]]; then
    dry "Se aseguraria directorio de wallpapers: $dst_dir"
  else
    mkdir -p "$dst_dir"
  fi
  if [[ ! -d "$src_dir" ]]; then
    warn "No existe el directorio de wallpapers en el repo: $src_dir"
    echo ""
    return 0
  fi

  shopt -s nullglob
  local files=("$src_dir"/*)
  shopt -u nullglob

  if ((${#files[@]} == 0)); then
    warn "No hay wallpapers para copiar en: $src_dir"
    echo ""
    return 0
  fi

  local f
  for f in "${files[@]}"; do
    if [[ -f "$f" ]]; then
      local target_file="${dst_dir}/$(basename "$f")"
      if [[ ! -e "$target_file" ]]; then
        if [[ $DRY_RUN -eq 1 ]]; then
          dry "Se copiaria wallpaper: $target_file"
        else
          cp -a "$f" "$target_file"
          log "Wallpaper copiado: $target_file"
        fi
      fi
    fi
  done

  echo "$dst_dir"
}

ensure_wal_alacritty_template() {
  local content
  content="$(cat <<'EOF'
# Auto-generated by pywal

[colors.primary]
background = "{background}"
foreground = "{foreground}"

[colors.cursor]
text = "{background}"
cursor = "{foreground}"

[colors.normal]
black   = "{color0}"
red     = "{color1}"
green   = "{color2}"
yellow  = "{color3}"
blue    = "{color4}"
magenta = "{color5}"
cyan    = "{color6}"
white   = "{color7}"

[colors.bright]
black   = "{color8}"
red     = "{color9}"
green   = "{color10}"
yellow  = "{color11}"
blue    = "{color12}"
magenta = "{color13}"
cyan    = "{color14}"
white   = "{color15}"
EOF
)"

  if [[ $DRY_RUN -eq 1 ]]; then
    dry "Se aseguraria directorio de templates de wal: $WAL_TEMPLATES_DIR"
  else
    mkdir -p "$WAL_TEMPLATES_DIR"
  fi

  if [[ -f "$WAL_ALACRITTY_TEMPLATE" ]]; then
    local current
    current="$(cat "$WAL_ALACRITTY_TEMPLATE")"
    if [[ "$current" == "$content" ]]; then
      log "Template de Alacritty para wal ya esta actualizado: $WAL_ALACRITTY_TEMPLATE"
      return 0
    fi
  fi

  safe_write_file "$WAL_ALACRITTY_TEMPLATE" "$content"
  log "Template de Alacritty para wal asegurado en: $WAL_ALACRITTY_TEMPLATE"
}

regenerate_wal_cache() {
  local wallpaper_dir="$1"

  if ! command_exists wal; then
    warn "No se encontro wal (pywal). Se omite regenerar cache de colores."
    return 0
  fi

  if [[ -z "$wallpaper_dir" || ! -d "$wallpaper_dir" ]]; then
    warn "Directorio de wallpapers no valido para wal: $wallpaper_dir"
    return 0
  fi

  if [[ $DRY_RUN -eq 1 ]]; then
    dry "Se ejecutaria: wal -i $wallpaper_dir"
    return 0
  fi

  if wal -i "$wallpaper_dir"; then
    log "Cache de wal regenerada usando: $wallpaper_dir"
  else
    warn "wal no pudo regenerar la cache con: $wallpaper_dir"
  fi
}

ensure_alacritty_wal_import() {
  local base_colors_import='~/.config/alacritty/colors-base.toml'
  local wal_import='~/.cache/wal/colors-alacritty.toml'
  local import_line
  import_line="import = [\"${base_colors_import}\", \"${wal_import}\"]"

  local default_colors_content
  default_colors_content="$(cat <<'EOF'
[colors.primary]
background = "0x2E3440"
foreground = "0xD8DEE9"

[colors.normal]
black = "0x3B4252"
red = "0xBF616A"
green = "0xA3BE8C"
yellow = "0xEBCB8B"
blue = "0x81A1C1"
magenta = "0xB48EAD"
cyan = "0x88C0D0"
white = "0xE5E9F0"

[colors.bright]
black = "0x4C566A"
red = "0xBF616A"
green = "0xA3BE8C"
yellow = "0xEBCB8B"
blue = "0x81A1C1"
magenta = "0xB48EAD"
cyan = "0x8FBCBB"
white = "0xECEFF4"
EOF
)"

  if [[ ! -f "$ALACRITTY_CONFIG_FILE" ]]; then
    local content
    content="$(cat <<EOF
[general]
$import_line
EOF
)"
    safe_write_file "$ALACRITTY_BASE_COLORS_FILE" "$default_colors_content"
    safe_write_file "$ALACRITTY_CONFIG_FILE" "$content"
    log "Creado config de Alacritty con imports y paleta base: $ALACRITTY_CONFIG_FILE"
    return 0
  fi

  local tmp_config
  local tmp_colors
  local extracted=0
  local extracted_colors=""

  tmp_config="$(mktemp)"
  tmp_colors="$(mktemp)"

  awk -v colors_out="$tmp_colors" '
    BEGIN {
      in_colors = 0
      found_colors = 0
    }

    function is_section(line) {
      return line ~ /^[[:space:]]*\[[^]]+\][[:space:]]*$/
    }

    function is_colors_section(line) {
      return line ~ /^[[:space:]]*\[colors(\.[^]]+)?\][[:space:]]*$/
    }

    {
      if (is_section($0)) {
        if (is_colors_section($0)) {
          in_colors = 1
          found_colors = 1
        } else {
          in_colors = 0
        }
      }

      if (in_colors) {
        print >> colors_out
        next
      }

      print
    }

    END {
      if (found_colors) {
        exit 10
      }
      exit 0
    }
  ' "$ALACRITTY_CONFIG_FILE" > "$tmp_config" || extracted=$?

  if [[ $extracted -eq 10 && -s "$tmp_colors" ]]; then
    extracted_colors="$(cat "$tmp_colors")"
    safe_write_file "$ALACRITTY_BASE_COLORS_FILE" "$extracted_colors"

    if [[ $DRY_RUN -eq 1 ]]; then
      dry "Se extraerian bloques [colors.*] a: $ALACRITTY_BASE_COLORS_FILE"
    else
      if ! cmp -s "$ALACRITTY_CONFIG_FILE" "$tmp_config"; then
        backup_file_once "$ALACRITTY_CONFIG_FILE"
        cat "$tmp_config" > "$ALACRITTY_CONFIG_FILE"
        log "Bloques [colors.*] extraidos de Alacritty hacia: $ALACRITTY_BASE_COLORS_FILE"
      fi
    fi
  elif [[ ! -f "$ALACRITTY_BASE_COLORS_FILE" ]]; then
    safe_write_file "$ALACRITTY_BASE_COLORS_FILE" "$default_colors_content"
    log "Creada paleta base por defecto en: $ALACRITTY_BASE_COLORS_FILE"
  elif [[ $extracted -ne 0 ]]; then
    warn "No se pudo analizar $ALACRITTY_CONFIG_FILE para extraer [colors.*]."
  fi

  rm -f "$tmp_config" "$tmp_colors"

  if [[ $DRY_RUN -eq 1 ]]; then
    dry "Se aseguraria import en orden (base, wal) en: $ALACRITTY_CONFIG_FILE"
    return 0
  fi

  local tmp
  tmp="$(mktemp)"

  awk -v import_line="$import_line" '
    BEGIN {
      in_general = 0
      general_seen = 0
      import_set = 0
    }

    /^[[:space:]]*\[[^]]+\][[:space:]]*$/ {
      if (in_general && !import_set) {
        print import_line
        import_set = 1
      }

      if ($0 ~ /^[[:space:]]*\[general\][[:space:]]*$/) {
        in_general = 1
        general_seen = 1
      } else {
        in_general = 0
      }

      print
      next
    }

    {
      if (in_general && $0 ~ /^[[:space:]]*import[[:space:]]*=/) {
        print import_line
        import_set = 1
        next
      }

      print
    }

    END {
      if (!general_seen) {
        print ""
        print "[general]"
        print import_line
      } else if (in_general && !import_set) {
        print import_line
      }
    }
  ' "$ALACRITTY_CONFIG_FILE" > "$tmp"

  if ! cmp -s "$ALACRITTY_CONFIG_FILE" "$tmp"; then
    backup_file_once "$ALACRITTY_CONFIG_FILE"
    cat "$tmp" > "$ALACRITTY_CONFIG_FILE"
    log "Agregado import de wal en Alacritty: $ALACRITTY_CONFIG_FILE"
  else
    log "Alacritty ya estaba en estado correcto: $ALACRITTY_CONFIG_FILE"
  fi

  rm -f "$tmp"
}
